# Configuración de Fly.io para factura-justa-api

primary_region = "mad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  # Healthcheck HTTP cada 15s contra la raíz
  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    timeout = "5s"
    method = "GET"
    path = "/"
    protocol = "http"

# Señal y tiempo de apagado para paradas más limpias
kill_signal = "SIGTERM"
kill_timeout = "30s"

# Ejecutar migraciones antes del arranque de la versión (máquina temporal)
[deploy]
  release_command = "node ace migration:run --force"
