name: deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    env:
      FLY_APP_NAME: factura-justa-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy (Nixpacks)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --nixpacks -a "$FLY_APP_NAME" --now --strategy immediate
